name: provision-ec2

on:
  workflow_dispatch:

jobs:
  tf_provision:
    name: Terraform provision EC2 instance
    runs-on: ubuntu-latest
    outputs:
      public_dns: ${{ steps.apply.outputs.public_dns }}
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6
          terraform_wrapper: false

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init
      
      - name: Terraform plan
        working-directory: ./terraform
        run: |
          terraform plan -input=false -no-color -out tf.plan

      - name: Terraform apply
        working-directory: ./terraform
        id: apply
        run: terraform apply -input=false tf.plan 
